### ISSUE TITLE
Feed API

### ISSUE THREAD

**Issue by osterwood** [CMU-CREATE-Lab/specksensor.com#1]
Hi,

I was wondering if you had any examples or documentation on how to use the Speck API to query recent values uploaded by my Speck to the site.  I see that there is "API Key (read-only)", how is that used exactly via web requests?

Thanks!

**Comment by tasota** [comment]
Hey there!

The app utilizes an open source tool known as "esdr" which is maintained by the CMU CREATE Lab team on GitHub. The documentation for the API that the app uses can be found on its GitHub page:

https://github.com/CMU-CREATE-Lab/esdr

**Comment by chrisbartley** [comment]
Thanks for supporting Speck, and thanks for the question!  We do indeed have an API you can use.  We don't have methods for editing/deleting items yet (coming soon!), but there's good support for pulling data, so it should be sufficient for your needs.

The specksensor.com site stores all its data--both user data and speck data--in an open source data repository we developed and host called the Environmental Sensor Data Repository (ESDR).  We needed a way to store lots of data and retrieve it quickly (with support for fast aggregation), and existing solutions such as Xively, Cloudant, etc. either didn't have the features we needed or the price was simply out of our reach (academia!).  So we built our own. Anyway, I'd recommend starting with the overview here:

https://github.com/CMU-CREATE-Lab/esdr/blob/master/README.md

Our API docs are a little lacking, but a number of the methods are documented here:

https://github.com/CMU-CREATE-Lab/esdr/blob/master/HOW_TO.md

For generating reports, I'd recommend the export method, documented here:

https://github.com/CMU-CREATE-Lab/esdr/blob/master/HOW_TO.md#export

Export is currently CSV only, but we'll be adding JSON soon.

If all you care about is the most recent value(s)--for example, if you're polling it every few minutes--it probably makes sense to use the most-recent method instead, e.g.:

	https://esdr.cmucreatelab.org/api/v1/feeds/FEED_ID_OR_API_KEY/most-recent

Or, for a single channel:

	https://esdr.cmucreatelab.org/api/v1/feeds/FEED_ID_OR_API_KEY/channels/CHANNEL_NAME/most-recent

Don't hesitate to let me know if you have questions.

**Comment by osterwood** [comment]
Chris -- thanks so much for the detailed reply.  This is perfect.  I was looking through the source of the this repo for this kind of information -- didn't realize it was in the esdr repo.

**Comment by chrisbartley** [comment]
Good, glad it helped.  I'll eventually add *good* API docs to both ESDR and specksensor.com, but it's a few months off since there's still a bit of work to do to flesh out ESDR's API.

There are a few ESDR API methods that simply aren't documented at all, so let me know if you can't find what you need.
